// Phase 21.3d-parity-α · Deterministic golden envelope for `BacktestResult`.
//
// Hand-authored full-shape literal that MUST compile against the production
// type from `../../backtest.functions`. Any field rename, deletion, or type
// change in production will surface as a TS error here — that's the shape
// lock. Value contents are chosen to exercise:
//   • BUY / SELL / WAIT signals
//   • WIN / LOSS / FLAT / SKIP / AMBIGUOUS / INVALID_SETUP outcomes
//   • ambiguous both-touched trade
//   • fabricatedLevels branch
//   • costs / slippage (non-zero + zero)
//   • benchmark computation
//   • dataQuality with missing/invalid sessions
//   • best/worst month + best/worst insights across nakshatra/moonSign/retro
//   • ambiguousCount / invalidSetupCount counters
//
// The Run-ID is the exact output of `computeRunId` for the input below; if it
// ever changes we will detect it in `run-id-oracle.test.ts`.

import type { BacktestResult } from "../../backtest.functions";
import {
  BACKTEST_ENGINE_VERSION,
  BACKTEST_FORMULA_VERSION,
  computeRunId as computeLegacyBacktestRunId,
  hashConfig,
} from "../../backtest-engine";
import { DEFAULT_ASTRO_FORMULA_VERSION } from "../../engine-version";

export const BACKTEST_GOLDEN_INPUT = {
  symbol: "NIFTY50" as const,
  from: "2026-04-01",
  to: "2026-06-30",
  policy: "conservative" as const,
  invalidSetupPolicy: "fabricate" as const,
  costs: { slippagePct: 0, brokerageFlat: 0, brokeragePct: 0, taxesPct: 0 },
  dataSource: "Yahoo Finance (daily, unadjusted OHLC)",
  timezone: "Asia/Kolkata",
};

export const BACKTEST_GOLDEN_RUN_ID = computeLegacyBacktestRunId({
  symbol: BACKTEST_GOLDEN_INPUT.symbol,
  from: BACKTEST_GOLDEN_INPUT.from,
  to: BACKTEST_GOLDEN_INPUT.to,
  policy: BACKTEST_GOLDEN_INPUT.policy,
  invalidSetupPolicy: BACKTEST_GOLDEN_INPUT.invalidSetupPolicy,
  costs: BACKTEST_GOLDEN_INPUT.costs,
  dataSource: BACKTEST_GOLDEN_INPUT.dataSource,
  timezone: BACKTEST_GOLDEN_INPUT.timezone,
  astroFormulaVersion: DEFAULT_ASTRO_FORMULA_VERSION,
});

export const BACKTEST_GOLDEN_CONFIG_HASH = hashConfig({
  symbol: BACKTEST_GOLDEN_INPUT.symbol,
  from: BACKTEST_GOLDEN_INPUT.from,
  to: BACKTEST_GOLDEN_INPUT.to,
  policy: BACKTEST_GOLDEN_INPUT.policy,
  invalidSetupPolicy: BACKTEST_GOLDEN_INPUT.invalidSetupPolicy,
  costs: BACKTEST_GOLDEN_INPUT.costs,
});

/** Fixed generatedAt for deterministic byte-oracle comparison. */
export const BACKTEST_GOLDEN_GENERATED_AT = "2026-07-15T00:00:00.000Z";

/**
 * Full-shape `BacktestResult` literal. Every optional field is populated so
 * that a future change of a field type from `T | undefined` to `T` (or the
 * reverse) surfaces immediately.
 */
export const BACKTEST_GOLDEN: BacktestResult = {
  symbol: "NIFTY50",
  yahooSymbol: "^NSEI",
  label: "NIFTY 50",
  from: BACKTEST_GOLDEN_INPUT.from,
  to: BACKTEST_GOLDEN_INPUT.to,
  candles: 3,
  trades: [
    {
      date: "2026-04-02",
      time: "09:15",
      symbol: "NIFTY50",
      signal: "BUY",
      strength: "STRONG",
      confidence: 82,
      entry: 22000,
      exit: 22100,
      high: 22150,
      low: 21980,
      target: 22100,
      stop: 21950,
      targetHit: true,
      stopHit: false,
      result: "WIN",
      pnl: 100,
      pnlPct: 0.45,
      moonSign: "Aries",
      moonNakshatra: "Ashwini",
      retroCount: 2,
      nearest: "Sun R1",
      dayOfWeek: "Thu",
      month: "2026-04",
      ambiguous: false,
      fabricatedLevels: false,
      grossPnl: 100,
      netPnl: 100,
      costs: 0,
      astroTs: "2026-04-02T03:30:00.000Z",
      entryTs: "2026-04-02T03:45:00.000Z",
      exitTs: "2026-04-02T10:00:00.000Z",
      dataAvailableTs: "2026-04-01T18:29:00.000Z",
    },
    {
      date: "2026-04-03",
      time: "09:15",
      symbol: "NIFTY50",
      signal: "SELL",
      strength: "MEDIUM",
      confidence: 65,
      entry: 22100,
      exit: 22050,
      high: 22160,
      low: 21990,
      target: 21990,
      stop: 22160,
      targetHit: true,
      stopHit: true,
      result: "LOSS",
      pnl: -60,
      pnlPct: -0.27,
      moonSign: "Taurus",
      moonNakshatra: "Bharani",
      retroCount: 2,
      nearest: "Moon S1",
      dayOfWeek: "Fri",
      month: "2026-04",
      ambiguous: true,
      fabricatedLevels: false,
      grossPnl: -60,
      netPnl: -60,
      costs: 0,
      astroTs: "2026-04-03T03:30:00.000Z",
      entryTs: "2026-04-03T03:45:00.000Z",
      exitTs: "2026-04-03T10:00:00.000Z",
      dataAvailableTs: "2026-04-02T18:29:00.000Z",
    },
    {
      date: "2026-04-06",
      time: "09:15",
      symbol: "NIFTY50",
      signal: "WAIT",
      strength: "LOW",
      confidence: 40,
      entry: 22050,
      exit: 22040,
      high: 22080,
      low: 22030,
      target: null,
      stop: null,
      targetHit: false,
      stopHit: false,
      result: "SKIP",
      pnl: 0,
      pnlPct: 0,
      moonSign: "Taurus",
      moonNakshatra: "Bharani",
      retroCount: 2,
      nearest: null,
      dayOfWeek: "Mon",
      month: "2026-04",
      ambiguous: false,
      fabricatedLevels: false,
      grossPnl: 0,
      netPnl: 0,
      costs: 0,
      astroTs: "2026-04-06T03:30:00.000Z",
      entryTs: "2026-04-06T03:45:00.000Z",
      exitTs: "2026-04-06T10:00:00.000Z",
      dataAvailableTs: "2026-04-03T18:29:00.000Z",
    },
  ],
  summary: {
    totalSignals: 3,
    buy: 1,
    sell: 1,
    wait: 1,
    taken: 2,
    wins: 1,
    losses: 1,
    flats: 0,
    winRate: 50,
    lossRate: 50,
    accuracy: 50,
    avgProfit: 100,
    avgLoss: 60,
    profitFactor: 1.67,
    netProfit: 40,
    maxDrawdown: 60,
    maxConsecWins: 1,
    maxConsecLosses: 1,
    avgHoldingDays: 1,
    bestMonth: { month: "2026-04", pnl: 40 },
    worstMonth: { month: "2026-04", pnl: 40 },
  },
  monthly: [
    {
      month: "2026-04",
      trades: 2,
      wins: 1,
      losses: 1,
      pnl: 40,
      accuracy: 50,
    },
  ],
  insights: {
    bestNakshatra: { key: "Ashwini", trades: 1, wins: 1, winRate: 100, pnl: 100 },
    worstNakshatra: { key: "Bharani", trades: 1, wins: 0, winRate: 0, pnl: -60 },
    bestMoonSign: { key: "Aries", trades: 1, wins: 1, winRate: 100, pnl: 100 },
    worstMoonSign: { key: "Taurus", trades: 1, wins: 0, winRate: 0, pnl: -60 },
    bestRetroCombo: { key: "2 retro", trades: 2, wins: 1, winRate: 50, pnl: 40 },
    worstRetroCombo: { key: "2 retro", trades: 2, wins: 1, winRate: 50, pnl: 40 },
    mostSuccessfulSignal: { key: "BUY", trades: 1, wins: 1, winRate: 100, pnl: 100 },
    mostFailedSignal: { key: "SELL", trades: 1, wins: 0, winRate: 0, pnl: -60 },
  },
  equityCurve: [
    { date: "2026-04-02", cumulative: 100 },
    { date: "2026-04-03", cumulative: 40 },
    { date: "2026-04-06", cumulative: 40 },
  ],
  generatedAt: BACKTEST_GOLDEN_GENERATED_AT,
  runId: BACKTEST_GOLDEN_RUN_ID,
  engineVersion: BACKTEST_ENGINE_VERSION,
  formulaVersion: BACKTEST_FORMULA_VERSION,
  astroFormulaVersion: DEFAULT_ASTRO_FORMULA_VERSION,
  configHash: BACKTEST_GOLDEN_CONFIG_HASH,
  executionMeta: {
    policy: BACKTEST_GOLDEN_INPUT.policy,
    invalidSetupPolicy: BACKTEST_GOLDEN_INPUT.invalidSetupPolicy,
    costs: BACKTEST_GOLDEN_INPUT.costs,
    astroAnchor: "09:00 IST",
    entryTime: "09:15 IST",
    exitAssumption: "target / stop within daily OHLC; else session close",
    dataSource: BACKTEST_GOLDEN_INPUT.dataSource,
    timezone: BACKTEST_GOLDEN_INPUT.timezone,
    candleTimeframe: "1d",
  },
  dataQuality: {
    expectedSessions: 65,
    loadedSessions: 3,
    missingSessions: 62,
    invalidSessions: 1,
    coveragePct: 4.6,
    dataSource: BACKTEST_GOLDEN_INPUT.dataSource,
    adjusted: "unadjusted",
  },
  stats: {
    sampleSize: 2,
    sampleWarning: "INSUFFICIENT",
    expectancy: 20,
    median: 20,
    stddev: 113.14,
    sharpeLike: 0.18,
    sortinoLike: 0,
    payoffRatio: 1.67,
    recoveryFactor: 0.67,
    exposurePct: 66.67,
  },
  benchmark: {
    buyAndHoldPnl: 40,
    buyAndHoldPct: 0.18,
    strategyPct: 0.18,
    excessPct: 0,
    activeDays: 2,
  },
  ambiguousCount: 1,
  invalidSetupCount: 0,
  disclaimers: [
    "Historical results are simulated and depend on candle resolution, execution assumptions, data quality, slippage, and costs.",
    "Daily OHLC data cannot determine intraday event order — the both-touched case is resolved per the selected execution policy.",
    "Backtests are informational and do not guarantee future performance.",
  ],
};

/** Enumerated set of top-level keys expected on `BacktestResult`. */
export const BACKTEST_RESULT_KEYS = [
  "symbol",
  "yahooSymbol",
  "label",
  "from",
  "to",
  "candles",
  "trades",
  "summary",
  "monthly",
  "insights",
  "equityCurve",
  "generatedAt",
  "runId",
  "engineVersion",
  "formulaVersion",
  "astroFormulaVersion",
  "configHash",
  "executionMeta",
  "dataQuality",
  "stats",
  "benchmark",
  "ambiguousCount",
  "invalidSetupCount",
  "disclaimers",
] as const;

export const BACKTEST_TRADE_KEYS = [
  "date",
  "time",
  "symbol",
  "signal",
  "strength",
  "confidence",
  "entry",
  "exit",
  "high",
  "low",
  "target",
  "stop",
  "targetHit",
  "stopHit",
  "result",
  "pnl",
  "pnlPct",
  "moonSign",
  "moonNakshatra",
  "retroCount",
  "nearest",
  "dayOfWeek",
  "month",
  "ambiguous",
  "fabricatedLevels",
  "grossPnl",
  "netPnl",
  "costs",
  "astroTs",
  "entryTs",
  "exitTs",
  "dataAvailableTs",
] as const;

export const BACKTEST_SUMMARY_KEYS = [
  "totalSignals",
  "buy",
  "sell",
  "wait",
  "taken",
  "wins",
  "losses",
  "flats",
  "winRate",
  "lossRate",
  "accuracy",
  "avgProfit",
  "avgLoss",
  "profitFactor",
  "netProfit",
  "maxDrawdown",
  "maxConsecWins",
  "maxConsecLosses",
  "avgHoldingDays",
  "bestMonth",
  "worstMonth",
] as const;

export const BACKTEST_EXECUTION_META_KEYS = [
  "policy",
  "invalidSetupPolicy",
  "costs",
  "astroAnchor",
  "entryTime",
  "exitAssumption",
  "dataSource",
  "timezone",
  "candleTimeframe",
] as const;

export const BACKTEST_DATA_QUALITY_KEYS = [
  "expectedSessions",
  "loadedSessions",
  "missingSessions",
  "invalidSessions",
  "coveragePct",
  "dataSource",
  "adjusted",
] as const;

export const BACKTEST_INSIGHTS_KEYS = [
  "bestNakshatra",
  "worstNakshatra",
  "bestMoonSign",
  "worstMoonSign",
  "bestRetroCombo",
  "worstRetroCombo",
  "mostSuccessfulSignal",
  "mostFailedSignal",
] as const;

export const BACKTEST_STATS_KEYS = [
  "sampleSize",
  "sampleWarning",
  "expectancy",
  "median",
  "stddev",
  "sharpeLike",
  "sortinoLike",
  "payoffRatio",
  "recoveryFactor",
  "exposurePct",
] as const;

export const BACKTEST_BENCHMARK_KEYS = [
  "buyAndHoldPnl",
  "buyAndHoldPct",
  "strategyPct",
  "excessPct",
  "activeDays",
] as const;