/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalAccuracyRouteImport } from './routes/signal-accuracy'
import { Route as OptionStrategyRouteImport } from './routes/option-strategy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LiveTerminalRouteImport } from './routes/live-terminal'
import { Route as LiveMarketTerminalRouteImport } from './routes/live-market-terminal'
import { Route as LiveLevelsRouteImport } from './routes/live-levels'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AstroRouteImport } from './routes/astro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevDiagnosticsRouteImport } from './routes/dev.diagnostics'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SignalAccuracyRoute = SignalAccuracyRouteImport.update({
  id: '/signal-accuracy',
  path: '/signal-accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionStrategyRoute = OptionStrategyRouteImport.update({
  id: '/option-strategy',
  path: '/option-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTerminalRoute = LiveTerminalRouteImport.update({
  id: '/live-terminal',
  path: '/live-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMarketTerminalRoute = LiveMarketTerminalRouteImport.update({
  id: '/live-market-terminal',
  path: '/live-market-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLevelsRoute = LiveLevelsRouteImport.update({
  id: '/live-levels',
  path: '/live-levels',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroRoute = AstroRouteImport.update({
  id: '/astro',
  path: '/astro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiagnosticsRoute = DevDiagnosticsRouteImport.update({
  id: '/dev/diagnostics',
  path: '/dev/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astro': typeof AstroRoute
  '/backtest': typeof BacktestRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astro': typeof AstroRoute
  '/backtest': typeof BacktestRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astro': typeof AstroRoute
  '/backtest': typeof BacktestRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astro'
    | '/backtest'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/signal-accuracy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astro'
    | '/backtest'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/signal-accuracy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/astro'
    | '/backtest'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/signal-accuracy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstroRoute: typeof AstroRoute
  BacktestRoute: typeof BacktestRoute
  LiveLevelsRoute: typeof LiveLevelsRoute
  LiveMarketTerminalRoute: typeof LiveMarketTerminalRoute
  LiveTerminalRoute: typeof LiveTerminalRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  OptionStrategyRoute: typeof OptionStrategyRoute
  SignalAccuracyRoute: typeof SignalAccuracyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DevDiagnosticsRoute: typeof DevDiagnosticsRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signal-accuracy': {
      id: '/signal-accuracy'
      path: '/signal-accuracy'
      fullPath: '/signal-accuracy'
      preLoaderRoute: typeof SignalAccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option-strategy': {
      id: '/option-strategy'
      path: '/option-strategy'
      fullPath: '/option-strategy'
      preLoaderRoute: typeof OptionStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-terminal': {
      id: '/live-terminal'
      path: '/live-terminal'
      fullPath: '/live-terminal'
      preLoaderRoute: typeof LiveTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-market-terminal': {
      id: '/live-market-terminal'
      path: '/live-market-terminal'
      fullPath: '/live-market-terminal'
      preLoaderRoute: typeof LiveMarketTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-levels': {
      id: '/live-levels'
      path: '/live-levels'
      fullPath: '/live-levels'
      preLoaderRoute: typeof LiveLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro': {
      id: '/astro'
      path: '/astro'
      fullPath: '/astro'
      preLoaderRoute: typeof AstroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/diagnostics': {
      id: '/dev/diagnostics'
      path: '/dev/diagnostics'
      fullPath: '/dev/diagnostics'
      preLoaderRoute: typeof DevDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstroRoute: AstroRoute,
  BacktestRoute: BacktestRoute,
  LiveLevelsRoute: LiveLevelsRoute,
  LiveMarketTerminalRoute: LiveMarketTerminalRoute,
  LiveTerminalRoute: LiveTerminalRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  OptionStrategyRoute: OptionStrategyRoute,
  SignalAccuracyRoute: SignalAccuracyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DevDiagnosticsRoute: DevDiagnosticsRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
