/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignalAccuracyRouteImport } from './routes/signal-accuracy'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OptionsChainRouteImport } from './routes/options-chain'
import { Route as OptionsAnalyticsRouteImport } from './routes/options-analytics'
import { Route as OptionStrategyRouteImport } from './routes/option-strategy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketReplayRouteImport } from './routes/market-replay'
import { Route as LiveTerminalRouteImport } from './routes/live-terminal'
import { Route as LiveMarketTerminalRouteImport } from './routes/live-market-terminal'
import { Route as LiveLevelsRouteImport } from './routes/live-levels'
import { Route as DecisionRouteImport } from './routes/decision'
import { Route as BrokerRouteImport } from './routes/broker'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AstroRouteImport } from './routes/astro'
import { Route as AbsoluteIntradayValidationRouteImport } from './routes/absolute-intraday-validation'
import { Route as AbsoluteIntradayRouteImport } from './routes/absolute-intraday'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevDiagnosticsRouteImport } from './routes/dev.diagnostics'
import { Route as DevAstroFixtureCaptureRouteImport } from './routes/dev.astro-fixture-capture'
import { Route as DevAstroAuditRouteImport } from './routes/dev.astro-audit'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentStatusRouteImport } from './routes/_authenticated/payment-status'
import { Route as AuthenticatedLicenseRouteImport } from './routes/_authenticated/license'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminStagingValidationRouteImport } from './routes/_authenticated/admin.staging-validation'
import { Route as AuthenticatedAdminReadinessRouteImport } from './routes/_authenticated/admin.readiness'
import { Route as AuthenticatedAdminProvidersRouteImport } from './routes/_authenticated/admin.providers'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const SignalAccuracyRoute = SignalAccuracyRouteImport.update({
  id: '/signal-accuracy',
  path: '/signal-accuracy',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsChainRoute = OptionsChainRouteImport.update({
  id: '/options-chain',
  path: '/options-chain',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionsAnalyticsRoute = OptionsAnalyticsRouteImport.update({
  id: '/options-analytics',
  path: '/options-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OptionStrategyRoute = OptionStrategyRouteImport.update({
  id: '/option-strategy',
  path: '/option-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketReplayRoute = MarketReplayRouteImport.update({
  id: '/market-replay',
  path: '/market-replay',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTerminalRoute = LiveTerminalRouteImport.update({
  id: '/live-terminal',
  path: '/live-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMarketTerminalRoute = LiveMarketTerminalRouteImport.update({
  id: '/live-market-terminal',
  path: '/live-market-terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLevelsRoute = LiveLevelsRouteImport.update({
  id: '/live-levels',
  path: '/live-levels',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoute = DecisionRouteImport.update({
  id: '/decision',
  path: '/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRoute = BrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AstroRoute = AstroRouteImport.update({
  id: '/astro',
  path: '/astro',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsoluteIntradayValidationRoute =
  AbsoluteIntradayValidationRouteImport.update({
    id: '/absolute-intraday-validation',
    path: '/absolute-intraday-validation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AbsoluteIntradayRoute = AbsoluteIntradayRouteImport.update({
  id: '/absolute-intraday',
  path: '/absolute-intraday',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiagnosticsRoute = DevDiagnosticsRouteImport.update({
  id: '/dev/diagnostics',
  path: '/dev/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAstroFixtureCaptureRoute = DevAstroFixtureCaptureRouteImport.update({
  id: '/dev/astro-fixture-capture',
  path: '/dev/astro-fixture-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const DevAstroAuditRoute = DevAstroAuditRouteImport.update({
  id: '/dev/astro-audit',
  path: '/dev/astro-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentStatusRoute =
  AuthenticatedPaymentStatusRouteImport.update({
    id: '/payment-status',
    path: '/payment-status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLicenseRoute = AuthenticatedLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminStagingValidationRoute =
  AuthenticatedAdminStagingValidationRouteImport.update({
    id: '/admin/staging-validation',
    path: '/admin/staging-validation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReadinessRoute =
  AuthenticatedAdminReadinessRouteImport.update({
    id: '/admin/readiness',
    path: '/admin/readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProvidersRoute =
  AuthenticatedAdminProvidersRouteImport.update({
    id: '/admin/providers',
    path: '/admin/providers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absolute-intraday': typeof AbsoluteIntradayRoute
  '/absolute-intraday-validation': typeof AbsoluteIntradayValidationRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/broker': typeof BrokerRoute
  '/decision': typeof DecisionRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/market-replay': typeof MarketReplayRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/options-analytics': typeof OptionsAnalyticsRoute
  '/options-chain': typeof OptionsChainRoute
  '/pricing': typeof PricingRoute
  '/risk': typeof RiskRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/payment-status': typeof AuthenticatedPaymentStatusRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/dev/astro-audit': typeof DevAstroAuditRoute
  '/dev/astro-fixture-capture': typeof DevAstroFixtureCaptureRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/readiness': typeof AuthenticatedAdminReadinessRoute
  '/admin/staging-validation': typeof AuthenticatedAdminStagingValidationRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absolute-intraday': typeof AbsoluteIntradayRoute
  '/absolute-intraday-validation': typeof AbsoluteIntradayValidationRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/broker': typeof BrokerRoute
  '/decision': typeof DecisionRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/market-replay': typeof MarketReplayRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/options-analytics': typeof OptionsAnalyticsRoute
  '/options-chain': typeof OptionsChainRoute
  '/pricing': typeof PricingRoute
  '/risk': typeof RiskRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/license': typeof AuthenticatedLicenseRoute
  '/payment-status': typeof AuthenticatedPaymentStatusRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/dev/astro-audit': typeof DevAstroAuditRoute
  '/dev/astro-fixture-capture': typeof DevAstroFixtureCaptureRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/admin/readiness': typeof AuthenticatedAdminReadinessRoute
  '/admin/staging-validation': typeof AuthenticatedAdminStagingValidationRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/absolute-intraday': typeof AbsoluteIntradayRoute
  '/absolute-intraday-validation': typeof AbsoluteIntradayValidationRoute
  '/astro': typeof AstroRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/broker': typeof BrokerRoute
  '/decision': typeof DecisionRoute
  '/live-levels': typeof LiveLevelsRoute
  '/live-market-terminal': typeof LiveMarketTerminalRoute
  '/live-terminal': typeof LiveTerminalRoute
  '/market-replay': typeof MarketReplayRoute
  '/mcp': typeof McpRoute
  '/news': typeof NewsRoute
  '/option-strategy': typeof OptionStrategyRoute
  '/options-analytics': typeof OptionsAnalyticsRoute
  '/options-chain': typeof OptionsChainRoute
  '/pricing': typeof PricingRoute
  '/risk': typeof RiskRoute
  '/signal-accuracy': typeof SignalAccuracyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/license': typeof AuthenticatedLicenseRoute
  '/_authenticated/payment-status': typeof AuthenticatedPaymentStatusRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/dev/astro-audit': typeof DevAstroAuditRoute
  '/dev/astro-fixture-capture': typeof DevAstroFixtureCaptureRoute
  '/dev/diagnostics': typeof DevDiagnosticsRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/providers': typeof AuthenticatedAdminProvidersRoute
  '/_authenticated/admin/readiness': typeof AuthenticatedAdminReadinessRoute
  '/_authenticated/admin/staging-validation': typeof AuthenticatedAdminStagingValidationRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absolute-intraday'
    | '/absolute-intraday-validation'
    | '/astro'
    | '/auth'
    | '/backtest'
    | '/broker'
    | '/decision'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/market-replay'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/options-analytics'
    | '/options-chain'
    | '/pricing'
    | '/risk'
    | '/signal-accuracy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing'
    | '/license'
    | '/payment-status'
    | '/profile'
    | '/settings'
    | '/dev/astro-audit'
    | '/dev/astro-fixture-capture'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/readiness'
    | '/admin/staging-validation'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absolute-intraday'
    | '/absolute-intraday-validation'
    | '/astro'
    | '/auth'
    | '/backtest'
    | '/broker'
    | '/decision'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/market-replay'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/options-analytics'
    | '/options-chain'
    | '/pricing'
    | '/risk'
    | '/signal-accuracy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing'
    | '/license'
    | '/payment-status'
    | '/profile'
    | '/settings'
    | '/dev/astro-audit'
    | '/dev/astro-fixture-capture'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/readiness'
    | '/admin/staging-validation'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/absolute-intraday'
    | '/absolute-intraday-validation'
    | '/astro'
    | '/auth'
    | '/backtest'
    | '/broker'
    | '/decision'
    | '/live-levels'
    | '/live-market-terminal'
    | '/live-terminal'
    | '/market-replay'
    | '/mcp'
    | '/news'
    | '/option-strategy'
    | '/options-analytics'
    | '/options-chain'
    | '/pricing'
    | '/risk'
    | '/signal-accuracy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/billing'
    | '/_authenticated/license'
    | '/_authenticated/payment-status'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/dev/astro-audit'
    | '/dev/astro-fixture-capture'
    | '/dev/diagnostics'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/providers'
    | '/_authenticated/admin/readiness'
    | '/_authenticated/admin/staging-validation'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AbsoluteIntradayRoute: typeof AbsoluteIntradayRoute
  AbsoluteIntradayValidationRoute: typeof AbsoluteIntradayValidationRoute
  AstroRoute: typeof AstroRoute
  AuthRoute: typeof AuthRoute
  BacktestRoute: typeof BacktestRoute
  BrokerRoute: typeof BrokerRoute
  DecisionRoute: typeof DecisionRoute
  LiveLevelsRoute: typeof LiveLevelsRoute
  LiveMarketTerminalRoute: typeof LiveMarketTerminalRoute
  LiveTerminalRoute: typeof LiveTerminalRoute
  MarketReplayRoute: typeof MarketReplayRoute
  McpRoute: typeof McpRoute
  NewsRoute: typeof NewsRoute
  OptionStrategyRoute: typeof OptionStrategyRoute
  OptionsAnalyticsRoute: typeof OptionsAnalyticsRoute
  OptionsChainRoute: typeof OptionsChainRoute
  PricingRoute: typeof PricingRoute
  RiskRoute: typeof RiskRoute
  SignalAccuracyRoute: typeof SignalAccuracyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DevAstroAuditRoute: typeof DevAstroAuditRoute
  DevAstroFixtureCaptureRoute: typeof DevAstroFixtureCaptureRoute
  DevDiagnosticsRoute: typeof DevDiagnosticsRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signal-accuracy': {
      id: '/signal-accuracy'
      path: '/signal-accuracy'
      fullPath: '/signal-accuracy'
      preLoaderRoute: typeof SignalAccuracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options-chain': {
      id: '/options-chain'
      path: '/options-chain'
      fullPath: '/options-chain'
      preLoaderRoute: typeof OptionsChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/options-analytics': {
      id: '/options-analytics'
      path: '/options-analytics'
      fullPath: '/options-analytics'
      preLoaderRoute: typeof OptionsAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/option-strategy': {
      id: '/option-strategy'
      path: '/option-strategy'
      fullPath: '/option-strategy'
      preLoaderRoute: typeof OptionStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-replay': {
      id: '/market-replay'
      path: '/market-replay'
      fullPath: '/market-replay'
      preLoaderRoute: typeof MarketReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-terminal': {
      id: '/live-terminal'
      path: '/live-terminal'
      fullPath: '/live-terminal'
      preLoaderRoute: typeof LiveTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-market-terminal': {
      id: '/live-market-terminal'
      path: '/live-market-terminal'
      fullPath: '/live-market-terminal'
      preLoaderRoute: typeof LiveMarketTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-levels': {
      id: '/live-levels'
      path: '/live-levels'
      fullPath: '/live-levels'
      preLoaderRoute: typeof LiveLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision': {
      id: '/decision'
      path: '/decision'
      fullPath: '/decision'
      preLoaderRoute: typeof DecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astro': {
      id: '/astro'
      path: '/astro'
      fullPath: '/astro'
      preLoaderRoute: typeof AstroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absolute-intraday-validation': {
      id: '/absolute-intraday-validation'
      path: '/absolute-intraday-validation'
      fullPath: '/absolute-intraday-validation'
      preLoaderRoute: typeof AbsoluteIntradayValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absolute-intraday': {
      id: '/absolute-intraday'
      path: '/absolute-intraday'
      fullPath: '/absolute-intraday'
      preLoaderRoute: typeof AbsoluteIntradayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/diagnostics': {
      id: '/dev/diagnostics'
      path: '/dev/diagnostics'
      fullPath: '/dev/diagnostics'
      preLoaderRoute: typeof DevDiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/astro-fixture-capture': {
      id: '/dev/astro-fixture-capture'
      path: '/dev/astro-fixture-capture'
      fullPath: '/dev/astro-fixture-capture'
      preLoaderRoute: typeof DevAstroFixtureCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/astro-audit': {
      id: '/dev/astro-audit'
      path: '/dev/astro-audit'
      fullPath: '/dev/astro-audit'
      preLoaderRoute: typeof DevAstroAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment-status': {
      id: '/_authenticated/payment-status'
      path: '/payment-status'
      fullPath: '/payment-status'
      preLoaderRoute: typeof AuthenticatedPaymentStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/license': {
      id: '/_authenticated/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof AuthenticatedLicenseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/staging-validation': {
      id: '/_authenticated/admin/staging-validation'
      path: '/admin/staging-validation'
      fullPath: '/admin/staging-validation'
      preLoaderRoute: typeof AuthenticatedAdminStagingValidationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/readiness': {
      id: '/_authenticated/admin/readiness'
      path: '/admin/readiness'
      fullPath: '/admin/readiness'
      preLoaderRoute: typeof AuthenticatedAdminReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/providers': {
      id: '/_authenticated/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AuthenticatedAdminProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedLicenseRoute: typeof AuthenticatedLicenseRoute
  AuthenticatedPaymentStatusRoute: typeof AuthenticatedPaymentStatusRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProvidersRoute: typeof AuthenticatedAdminProvidersRoute
  AuthenticatedAdminReadinessRoute: typeof AuthenticatedAdminReadinessRoute
  AuthenticatedAdminStagingValidationRoute: typeof AuthenticatedAdminStagingValidationRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedLicenseRoute: AuthenticatedLicenseRoute,
  AuthenticatedPaymentStatusRoute: AuthenticatedPaymentStatusRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProvidersRoute: AuthenticatedAdminProvidersRoute,
  AuthenticatedAdminReadinessRoute: AuthenticatedAdminReadinessRoute,
  AuthenticatedAdminStagingValidationRoute:
    AuthenticatedAdminStagingValidationRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AbsoluteIntradayRoute: AbsoluteIntradayRoute,
  AbsoluteIntradayValidationRoute: AbsoluteIntradayValidationRoute,
  AstroRoute: AstroRoute,
  AuthRoute: AuthRoute,
  BacktestRoute: BacktestRoute,
  BrokerRoute: BrokerRoute,
  DecisionRoute: DecisionRoute,
  LiveLevelsRoute: LiveLevelsRoute,
  LiveMarketTerminalRoute: LiveMarketTerminalRoute,
  LiveTerminalRoute: LiveTerminalRoute,
  MarketReplayRoute: MarketReplayRoute,
  McpRoute: McpRoute,
  NewsRoute: NewsRoute,
  OptionStrategyRoute: OptionStrategyRoute,
  OptionsAnalyticsRoute: OptionsAnalyticsRoute,
  OptionsChainRoute: OptionsChainRoute,
  PricingRoute: PricingRoute,
  RiskRoute: RiskRoute,
  SignalAccuracyRoute: SignalAccuracyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DevAstroAuditRoute: DevAstroAuditRoute,
  DevAstroFixtureCaptureRoute: DevAstroFixtureCaptureRoute,
  DevDiagnosticsRoute: DevDiagnosticsRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
